FROM nginx:alpine AS production

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

COPY --from=builder /app/dist ./
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Run as root
CMD ["nginx", "-g", "daemon off;"]
